### ISSUE TITLE
Linking to the subsection doesn't seem to work

### ISSUE THREAD

**Issue by TimothyGillespie** [JavaWebStack/Passport#1]
**Describe the Bug**
On the page https://github.com/JavaWebStack/Passport/wiki/OAuth-Services-Custom-Responses the subsections are not linked as intended it seems

**To Reproduce**
Have eyes or an appropriate screen reader which reads out links and run it.

**Expected behavior**
It links.

**Screenshots / Logs**
None

**Environment Information:**
- Github [at the state of today]

**Additional Context**
None

**Comment by JulianFun123** [comment]
Fixed
